trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    submodules: true
  - task: NodeTool@0
    displayName: 'Install Node.js'
    inputs:
      versionSpec: '10.x'

  - script: |
      npm install
      npm run build
    displayName: 'npm install and build'
    workingDirectory: ''
  - task: AzureStaticWebApp@0
    inputs:
      app_location: '/dist'
      api_location: ''
      output_location: ''
    env:
      azure_static_web_apps_api_token: $(deployment_token)